### ISSUE TITLE
Поддержка ActionController::Parameters

### ISSUE THREAD

**Issue by michaelkhabarov** [corp-gp/active_dry_form#13]
Что думаете, если в https://github.com/corp-gp/active_dry_form/blob/master/lib/active_dry_form/form.rb#L71 переписать вот так: 

```diff
- raise 'in `params` use `request.parameters` instead of `params`' if params.is_a?(::ActionController::Parameters)
+ params = params.to_unsafe_h if params.is_a?(::ActionController::Parameters)
```

Тогда в контроллерах можно было бы вместо
```ruby
form = Form.new(params: request.parameters)
```
передавать напрямую `params`, выглядит чуть покрасивее и привычнее:
```ruby
form = Form.new(params: params)
```

**Comment by ermolaev** [comment]
https://github.com/rails/rails/blob/main/actionpack/lib/action_controller/metal/strong_parameters.rb#L1245

`params` довольно толстый объект, создание экземпляра `ActionController::Parameters` не быстрое, да и метод `to_unsafe_h` тоже медленный

так чуть многословнее получается, но зато намного производительнее

**Comment by xronos-i-am** [comment]
@ermolaev что думаешь, на счет настройки для params?

**Comment by ermolaev** [comment]
наверно да, для массового потребителя удобнее и понятнее `params`
