### ISSUE TITLE
Патч SchemaCompiler

### ISSUE THREAD

**Issue by xronos-i-am** [corp-gp/active_dry_form#6]
Тесты проходят и без этого кода `lib/active_dry_form/schema_compiler_patch.rb:17`. Актуален ли он?

```ruby
def visit_predicate(node, opts = {})
  name, rest = node

  key = opts[:key]

  case name
  when :key?
    keys[rest[0][1]] = { required: opts.fetch(:required, true) }
  when :array?
    keys[key][:array] = true
  else
    type = PREDICATE_TO_TYPE[name]
    keys[key][:type] = type if type
  end
end
```

**Comment by xronos-i-am** [comment]
А без этого не проходят, но совершенно не понятно, почему

```ruby
def visit_not(_node, opts = {})
  key = opts[:key]
  keys[key][:nullable] = true
end
```

**Comment by ermolaev** [comment]
появился новый extension https://dry-rb.org/gems/dry-schema/1.9/extensions/json_schema/ он фактически замена `Dry::Schema.load_extensions(:info)` но более расширенный, надо на него переписать

**Comment by xronos-i-am** [comment]
https://github.com/corp-gp/active_dry_form/pull/7
